"use client";
/* eslint-disable react-hooks/exhaustive-deps -- autosave intentionally keys off serialized draft and authoritative revision */
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { PWQE5_CONSENT_VERSION } from "@/lib/question-engine/pwqe5-contract";
import styles from "./assessment.module.css";
import { buildPwqe51DeepeningPreferences, buildPwqe51Response, buildTypedAssessmentResponse, familyLabel, isPwqe51AnswerValid, normaliseAssessmentState, PWQE51_DETAIL_PERMISSIONS, pwqe51AvailableStatuses, pwqe51QuestionPresentation, responseOrderForDraft, semanticOptionId, stateForHttpStatus, togglePwqe51Option, type AssessmentState, type Pwqe5RenderedInteraction, type Pwqe51ComparisonRelation, type Pwqe51RenderedInteraction, type RenderedInteraction, type RenderedOption } from "./ui-state";

const API="/api/assessment";
const previewItem: RenderedInteraction={instanceId:"preview-RL-101",bankItemId:"RL-101",family:"RL",stage:"S0",prompt:"People and roles to use today",helpText:"Choose the option that is easiest to answer today.",options:["A close friend","A family member","A partner or dating person","Another important person","No one fits right now"].map((label)=>({id:semanticOptionId("preview-RL-101",label),label}))};

export default function AssessmentPage(){
 const [state,setState]=useState<AssessmentState|null>(null),[failed,setFailed]=useState(false),[save,setSave]=useState(""),[preview,setPreview]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch(`${API}/state`,{cache:"no-store"});const unauthenticated=stateForHttpStatus(r.status);if(unauthenticated){setState(unauthenticated);setFailed(false);return}if(!r.ok)throw Error();setState(normaliseAssessmentState(await r.json()));setFailed(false)}catch{setFailed(true)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const request=useCallback(async(path:string,method:"POST"|"PUT",body:Record<string,unknown>,headers:Record<string,string>={})=>{if(!state||preview){setSave("Preview mode is not saved.");return}setSave("Saving…");try{const r=await fetch(`${API}/${path}`,{method,headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});if(r.status===409){setSave("Updated elsewhere — showing latest saved version.");return void load()}if(path==="complete-pass"&&r.status===503){setState({...state,reportUnavailable:true});setSave("Your answers are saved. Report preparation is temporarily unavailable.");return}if(!r.ok)throw Error();setState(normaliseAssessmentState(await r.json()));setSave("Saved")}catch{setSave("Could not save. Please try again.")}},[load,preview,state]);
 if(!state&&!failed)return <main className={styles.shell}><p className={styles.loading}>Preparing your private session…</p></main>;
 if(!state)return <Recovery retry={load} preview={()=>{setPreview(true);setState({status:"active",interaction:previewItem,mode:"preview"})}}/>;
 if(state.status==="needs_consent")return <Consent email={state.email} start={(email)=>request("start","POST",{email,consentVersion:PWQE5_CONSENT_VERSION})} preview={()=>{setPreview(true);setState({status:"active",interaction:previewItem,mode:"preview"})}}/>;
 if(state.status==="report_failed")return <ReportFailure state={state} reload={load}/>;
 if(state.status==="generating_pass1"||state.status==="generating_pass2")return <Generating state={state} pass={state.status.endsWith("pass1")?1:2} poll={load}/>;
 if(state.status==="pass1_ready"||state.status==="pass2_ready"||state.status==="report_ready")return <Boundary state={state} request={request}/>;
 if(state.status==="paused"||state.status==="recovery")return <Pause state={state} request={request}/>;
 if(state.interaction===null&&state.canCompletePass)return <Boundary state={state} request={request}/>;
 if(state.engine==="PWQE51"&&state.pwqe51Interaction)return <Pwqe51Question key={state.pwqe51Interaction.instanceId} state={state} item={state.pwqe51Interaction} request={request} save={save} preview={preview}/>;
 if(state.engine==="PWQE5"&&state.pwqe5Interaction)return <Pwqe5Question key={state.pwqe5Interaction.instanceId} state={state} item={state.pwqe5Interaction} request={request} save={save} preview={preview}/>;
 return <Question key={state.interaction?.instanceId??"preview"} state={state} request={request} save={save} preview={preview}/>;
}

function Pwqe51Question({state,item,request,save,preview}:{state:AssessmentState;item:Pwqe51RenderedInteraction;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>,h?:Record<string,string>)=>void;save:string;preview:boolean}){
 const initial=state.draft??{};
 const [value,setValue]=useState<Record<string,unknown>>(()=>initial);
 const lastSaved=useRef(JSON.stringify(initial));
 const selected=Array.isArray(value.selectedOptionIds)?value.selectedOptionIds.filter((entry):entry is string=>typeof entry==="string"):[];
 const set=(key:string,next:unknown)=>setValue((prior)=>({...prior,[key]:next}));
 const headers=()=>({"Idempotency-Key":crypto.randomUUID()});
 const payload=(completionState:"PARTIAL"|"COMPLETED"|"SKIPPED",status=String(value.status??"answered"))=>({
  expectedRevision:state.revision,
  interactionInstanceId:item.instanceId,
  bankItemId:item.bankItemId,
  completionState,
  response:buildPwqe51Response(value,item,status),
 });
 useEffect(()=>{const serialized=JSON.stringify(value);if(preview||(!selected.length&&!value.basis)||serialized===lastSaved.current)return;const timer=window.setTimeout(()=>{lastSaved.current=serialized;request("response","PUT",payload("PARTIAL"),headers())},700);return()=>window.clearTimeout(timer)},[item.instanceId,preview,request,state.revision,value]);
 const submit=(status:string)=>request("response","PUT",payload(status==="skip"?"SKIPPED":"COMPLETED",status),headers());
 const controls=new Map(item.responseControls.map((control)=>[control.id,control]));
 const selectedRole=typeof value.referentRole==="string"?item.referentRoleOptions.find((role)=>role.id===value.referentRole):undefined;
 const presentation=pwqe51QuestionPresentation(item,value);
 const noOtherPerson=presentation==="no_other_person";
 const showQuestion=presentation==="question";
 const roleChoicesVisible=item.referentSlotRequired===true&&presentation!=="unavailable_explanation";
 const allowPair=item.selection.allow_simultaneous_pair===true;
 const partialOrder=item.selection.mode==="partial_order";
 const canAnswer=isPwqe51AnswerValid(value,item);
 const choose=(id:string)=>setValue((prior)=>togglePwqe51Option(prior,item,id));
 const basisLabels:Record<string,string>={actual_recalled:"A specific situation I can recall",reported_typicality:"A pattern I recognize as typical"};
 return <main className={styles.shell}>
  <header className={styles.header}><div><p className={styles.kicker}>Patternwork · {item.stage==="mapping"?"Mapping":"Deepening"}</p><p className={styles.progressText}>Question {item.administrationSequence}. You can skip or pause whenever you need.</p>{state.mappingSummaryUrl&&<a href={state.mappingSummaryUrl}>Open your Mapping Summary</a>}</div><p className={styles.save} aria-live="polite">{preview?"Preview — not saved":save||"Saved automatically"}</p></header>
  {state.resumeNotificationStatus==="FAILED"?<ResumeEmailWarning/>:null}
  <div className={styles.stageBar} aria-label="Stage progress"><span style={{width:`${Math.max(8,Math.min(100,state.stageProgress??8))}%`}}/></div>
  <section className={styles.card} aria-labelledby="pwqe51-prompt">
   {roleChoicesVisible&&<fieldset><legend>{item.referentSlotPrompt??"Who was involved in the moment you are answering about?"}</legend><div className={styles.options}>{item.referentRoleOptions.map((role)=><button type="button" key={role.id} aria-pressed={selectedRole?.id===role.id} className={selectedRole?.id===role.id?styles.selected:styles.option} onClick={()=>setValue(()=>({referentRole:role.id,selectedOptionIds:[],mode:"single",basis:undefined}))}>{role.label}</button>)}</div></fieldset>}
   {presentation==="unavailable_explanation"?<h1 id="pwqe51-prompt">{item.prompt}</h1>:showQuestion?<><p className={styles.family}>{item.title} <span>· {item.context}</span></p><h1 id="pwqe51-prompt">{item.prompt}</h1>
    {item.rootBasisRequired&&<fieldset><legend>What kind of answer are you giving?</legend><div className={styles.options}>{item.basisOptions.map((basis)=><button type="button" key={basis} aria-pressed={value.basis===basis} className={value.basis===basis?styles.selected:styles.option} onClick={()=>set("basis",basis)}>{basisLabels[basis]??basis}</button>)}</div></fieldset>}
    <fieldset><legend>{partialOrder?"Select the responses that fit. Their order will be asked separately.":allowPair?"Choose one, or choose two only if both fit at the same time.":"Choose one answer."}</legend><div className={styles.options}>{item.options.map((option)=><button type="button" key={option.id} aria-pressed={selected.includes(option.id)} className={selected.includes(option.id)?styles.selected:styles.option} onClick={()=>choose(option.id)}>{option.label}</button>)}</div></fieldset>
    {partialOrder&&selected.length>1&&<fieldset><legend>How do the selected responses relate?</legend><div className={styles.options}>{[{id:"ordered",label:"I can say which came first"},{id:"order_unknown",label:"I cannot tell their order"}].map((choice)=><button type="button" key={choice.id} aria-pressed={value.mode===choice.id} className={value.mode===choice.id?styles.selected:styles.option} onClick={()=>set("mode",choice.id)}>{choice.label}</button>)}</div></fieldset>}
   </>:noOtherPerson?<p className={styles.small}>No other person or applicable situation was involved. Mark this not applicable, or skip the question.</p>:<p className={styles.small}>Choose a role to see the question. You can also skip it.</p>}
   <div className={styles.controls}>{pwqe51AvailableStatuses(item,value).filter((id)=>controls.has(id)).map((id)=><button className={styles.textButton} type="button" key={id} onClick={()=>submit(id)}>{controls.get(id)!.text}</button>)}{state.canPause&&<button className={styles.textButton} type="button" onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"pause"})}>Pause & save</button>}{state.allowedControls?.includes("shorten")&&<button className={styles.textButton} type="button" onClick={()=>request("control","POST",{expectedRevision:state.revision,action:"shorten"})}>Shorten this assessment</button>}{state.allowedControls?.includes("end")&&<button className={styles.textButton} type="button" onClick={()=>request("complete-pass","POST",{expectedRevision:state.revision,completedPass:state.pass,action:"end"})}>End now with what is supported</button>}{showQuestion&&!noOtherPerson&&<button className={styles.primary} type="button" disabled={!canAnswer} onClick={()=>submit("answered")}>Continue</button>}</div>
   {showQuestion&&<p className={styles.small}>“None of these fits,” “I am not sure,” and skipping are recorded separately. You can answer only what you can recall or recognize.</p>}
  </section>
 </main>;
}
function Consent({email,start,preview}:{email?:string;start:(email:string)=>void;preview:()=>void}){const [value,setValue]=useState(email??""),[ok,setOk]=useState(false),[error,setError]=useState("");function submit(e:FormEvent){e.preventDefault();if(!ok)return setError("Please confirm before continuing.");if(!/^\S+@\S+\.\S+$/.test(value))return setError("Enter an email address for your private resume link.");start(value.trim())}return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>Patternwork · private reflection</p><h1>A guided map of patterns that matter to you.</h1><p>This is not therapy, diagnosis, medical care, or an assessment of another person. You control what you share, may skip any prompt, and can pause whenever you need.</p><p>Selected options are categories, not your exact words.</p><form className={styles.form} onSubmit={submit}><label>Email for your private resume link<input type="email" value={value} onChange={e=>setValue(e.target.value)} required autoComplete="email"/></label><label className={styles.check}><input type="checkbox" checked={ok} onChange={e=>setOk(e.target.checked)}/>I understand this is a non-diagnostic reflection tool and I may pause, skip, or stop.</label>{error&&<p role="alert" className={styles.error}>{error}</p>}<button className={styles.primary}>Begin when ready</button></form><button className={styles.textButton} type="button" onClick={preview}>View the static test without saving</button><p className={styles.small}>If you feel in immediate danger or unable to stay safe, pause this tool and contact local emergency or crisis support.</p></section></main>}
function Question({state,request,save,preview}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>,h?:Record<string,string>)=>void;save:string;preview:boolean}){const item=state.interaction??previewItem;const initialDraft=state.draft??{};const [value,setValue]=useState<Record<string,unknown>>(()=>initialDraft),lastSaved=useRef(JSON.stringify(initialDraft));const responseHeaders=()=>({"Idempotency-Key":crypto.randomUUID()});const payload=(completionState:"PARTIAL"|"COMPLETED"|"SKIPPED")=>({expectedRevision:state.revision,interactionInstanceId:item.instanceId,bankItemId:item.bankItemId,completionState,response:buildTypedAssessmentResponse(item,value),responseOrder:responseOrderForDraft(value)});useEffect(()=>{const serialized=JSON.stringify(value);if(preview||!Object.keys(value).length||serialized===lastSaved.current)return;const timer=window.setTimeout(()=>{lastSaved.current=serialized;request("response","PUT",payload("PARTIAL"),responseHeaders())},700);return()=>window.clearTimeout(timer)},[item.bankItemId,item.instanceId,preview,request,state.revision,value]);const send=(completionState:"COMPLETED"|"SKIPPED")=>request("response","PUT",payload(completionState),responseHeaders());return <main className={styles.shell}><header className={styles.header}><div><p className={styles.kicker}>Patternwork · {state.stageLabel??`Stage ${item.stage.slice(1)}`}</p><p className={styles.progressText}>You’re moving through a few areas, at your own pace.</p>{state.mappingSummaryUrl&&<a href={state.mappingSummaryUrl}>Open your Mapping Summary</a>}</div><p className={styles.save} aria-live="polite">{preview?"Preview — not saved":save||"Saved automatically"}</p></header>{state.resumeNotificationStatus==="FAILED"?<ResumeEmailWarning/>:null}<div className={styles.stageBar} aria-label="Stage progress"><span style={{width:`${Math.max(8,Math.min(100,state.stageProgress??8))}%`}}/></div><section className={styles.card} aria-labelledby="prompt"><p className={styles.family}>{familyLabel(item.family)} <span>· optional detail</span></p><h1 id="prompt">{item.prompt}</h1>{item.helpText&&<p className={styles.help}>{item.helpText}</p>}<Renderer item={item} value={value} setValue={setValue}/><div className={styles.controls}><button className={styles.textButton} onClick={()=>send("SKIPPED")}>Skip</button><button className={styles.textButton} onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"pause"})}>Pause & save</button><button className={styles.primary} onClick={()=>send("COMPLETED")}>Continue</button></div><p className={styles.small}>“Not sure,” “none fit,” and “it depends” are useful answers.</p></section></main>}
function Pwqe5Question({state,item,request,save,preview}:{state:AssessmentState;item:Pwqe5RenderedInteraction;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>,h?:Record<string,string>)=>void;save:string;preview:boolean}){
 const initial=state.draft??{};
 const [value,setValue]=useState<Record<string,unknown>>(()=>initial);
 const [correctionOfResponseId,setCorrectionOfResponseId]=useState<string|undefined>();
 const lastSaved=useRef(JSON.stringify(initial));
 const history=state.responseHistory?.find((entry)=>entry.responseId===correctionOfResponseId);
 const question:Pwqe5RenderedInteraction=history?{...item,questionId:history.questionId,bankItemId:history.questionId,title:history.title,prompt:history.prompt??history.title,context:history.context??item.context,selection:history.selection??item.selection,responseControls:history.responseControls??item.responseControls,options:history.options??item.options}:item;
 const selected=Array.isArray(value.selectedOptionIds)?value.selectedOptionIds.filter((entry):entry is string=>typeof entry==="string"):[];
 const controls=new Map(question.responseControls.map((control)=>[control.id,control.text]));
 const set=(key:string,next:unknown)=>setValue((prior)=>({...prior,[key]:next}));
 const defaultMode="single";
 const mode=String(value.mode??defaultMode);
 const response=(status:string)=>({schemaVersion:"PWQE5-RS-1",status,mode:status==="answered"?mode:"single",selectedOptionIds:status==="answered"?selected:[],...(typeof value.note==="string"&&value.note.trim()?{privateNote:value.note}:{})});
 const headers=()=>({"Idempotency-Key":crypto.randomUUID()});
 const payload=(completionState:"PARTIAL"|"COMPLETED"|"SKIPPED",status=String(value.status??"answered"))=>({expectedRevision:state.revision,interactionInstanceId:item.instanceId,bankItemId:question.bankItemId,completionState,response:response(status),...(correctionOfResponseId?{correctionOfResponseId}:{})});
 useEffect(()=>{const serialized=JSON.stringify(value);if(preview||correctionOfResponseId||(!selected.length&&!String(value.note??""))||serialized===lastSaved.current)return;const timer=window.setTimeout(()=>{lastSaved.current=serialized;request("response","PUT",payload("PARTIAL"),headers())},700);return()=>window.clearTimeout(timer)},[item.instanceId,preview,request,state.revision,value,correctionOfResponseId]);
 const submit=(status:string)=>request("response","PUT",payload(status==="skip"?"SKIPPED":"COMPLETED",status),headers());
 const canAnswer=selected.length>0&&(selected.length<2||mode!=="single");
 const allowMulti=question.selection.mode==="partial_order"||question.selection.allow_simultaneous_pair===true;
 const maxSelect=question.selection.mode==="partial_order"?Number(question.selection.max_select??3):question.selection.allow_simultaneous_pair===true?2:1;
 const toggle=(id:string)=>{
  const option=question.options.find((candidate)=>candidate.id===id);if(!option)return;
  if(selected.includes(id)){const next=selected.filter((candidate)=>candidate!==id);set("selectedOptionIds",next);if(next.length<2)set("mode","single");return}
  const exclusive=question.options.find((candidate)=>candidate.exclusive&&selected.includes(candidate.id));
  const next=option.exclusive?[id]:[...selected.filter((selectedId)=>!question.options.find((candidate)=>candidate.id===selectedId)?.exclusive),id].slice(-maxSelect);
  if(exclusive&&!option.exclusive)set("selectedOptionIds",next);else if(!allowMulti)set("selectedOptionIds",[id]);else set("selectedOptionIds",next);
  if(question.selection.mode!=="partial_order"&&next.length>1)set("mode","simultaneous");
  else if(question.selection.mode!=="partial_order")set("mode","single");
  set("status","answered");
 };
 const relationshipModes=question.selection.mode==="partial_order"
  ?(selected.length<2?[]:[{id:"ordered",label:"In this order"},{id:"order_unknown",label:"I cannot tell the order"},...(question.selection.allow_simultaneous_pair===true?[{id:"simultaneous",label:"At the same time"}]:[])])
  :[{id:"single",label:"One answer"},...(question.selection.allow_simultaneous_pair===true?[{id:"simultaneous",label:"More than one fits"}]:[])];
 return <main className={styles.shell}>
  <header className={styles.header}><div><p className={styles.kicker}>Patternwork · {item.stage==="mapping"?"Mapping":"Deepening"}</p><p className={styles.progressText}>Question {item.administrationSequence}. You can skip or pause whenever you need.</p>{state.mappingSummaryUrl&&<a href={state.mappingSummaryUrl}>Open your Mapping Summary</a>}</div><p className={styles.save} aria-live="polite">{preview?"Preview — not saved":save||"Saved automatically"}</p></header>
  {state.resumeNotificationStatus==="FAILED"?<ResumeEmailWarning/>:null}
  <div className={styles.stageBar} aria-label="Stage progress"><span style={{width:`${Math.max(8,Math.min(100,state.stageProgress??8))}%`}}/></div>
   <section className={styles.card} aria-labelledby="pwqe5-prompt"><p className={styles.family}>{question.title} <span>· {question.context}</span></p><h1 id="pwqe5-prompt">{question.prompt}</h1>
   {state.responseHistory?.some((entry)=>entry.canCorrect)&&<details className={styles.history}><summary>Change an earlier answer</summary>{state.responseHistory.filter((entry)=>entry.canCorrect).map((entry)=><button className={styles.textButton} type="button" key={entry.responseId} onClick={()=>{setCorrectionOfResponseId(entry.responseId);setValue({selectedOptionIds:entry.selectedOptions.map((option)=>option.id),status:entry.status,mode:entry.mode??defaultMode});}}>{entry.title}</button>)}</details>}
   {correctionOfResponseId&&<p className={styles.small}>Editing an earlier answer. Saving will recheck later questions against the corrected answer.</p>}
   <fieldset><legend>{allowMulti?"Choose one or more that fit this moment.":"Choose the answer that fits this moment."}</legend><div className={styles.options}>{question.options.map((option)=><button type="button" key={option.id} className={selected.includes(option.id)?styles.selected:styles.option} aria-pressed={selected.includes(option.id)} onClick={()=>toggle(option.id)}>{option.label}</button>)}</div></fieldset>
   {relationshipModes.length>0&&<fieldset><legend>How do these answers relate?</legend><div className={styles.options}>{relationshipModes.map((choice)=><button type="button" key={choice.id} className={mode===choice.id?styles.selected:styles.option} aria-pressed={mode===choice.id} onClick={()=>set("mode",choice.id)}>{choice.label}</button>)}</div></fieldset>}
   <label className={styles.field}>Private note (optional)<textarea value={String(value.note??"")} onChange={(event)=>set("note",event.target.value)}/></label>
   <div className={styles.controls}>{question.responseControls.filter((control)=>control.id!=="skip").map((control)=><button className={styles.textButton} type="button" key={control.id} onClick={()=>submit(control.id)}>{control.text}</button>)}{controls.has("skip")&&<button className={styles.textButton} type="button" onClick={()=>submit("skip")}>{controls.get("skip")}</button>}{state.canPause&&<button className={styles.textButton} type="button" onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"pause"})}>Pause & save</button>}{state.allowedControls?.includes("shorten")&&<button className={styles.textButton} type="button" onClick={()=>request("control","POST",{expectedRevision:state.revision,action:"shorten"})}>Shorten this assessment</button>}{state.allowedControls?.includes("end")&&<button className={styles.textButton} type="button" onClick={()=>request("complete-pass","POST",{expectedRevision:state.revision,completedPass:state.pass,action:"end"})}>End now with what is supported</button>}<button className={styles.primary} type="button" disabled={!canAnswer} onClick={()=>submit("answered")}>{correctionOfResponseId?"Save correction":"Continue"}</button></div>
   <p className={styles.small}>Only the options you select become structured answers. Your private note is excluded from report generation.</p>
  </section>
 </main>;
}
function ResumeEmailWarning(){const [message,setMessage]=useState("We could not send your secure resume email. Your assessment is still saved on this device."),[sending,setSending]=useState(false);const resend=async()=>{setSending(true);try{const response=await fetch(`${API}/resend-resume`,{method:"POST"});setMessage(response.ok?"A new secure resume link was sent.":"We still could not send the link. Your work remains saved on this device.")}catch{setMessage("We still could not send the link. Your work remains saved on this device.")}finally{setSending(false)}};return <section className={styles.notificationWarning} role="status"><p>{message}</p><button className={styles.textButton} type="button" disabled={sending} onClick={()=>void resend()}>{sending?"Sending…":"Resend secure link"}</button></section>}
function Renderer({item,value,setValue}:{item:RenderedInteraction;value:Record<string,unknown>;setValue:(v:Record<string,unknown>)=>void}){const set=(key:string,v:unknown)=>setValue({...value,[key]:v}),options=item.options??[];let fields;if(item.family==="BTM")fields=<Body options={options} value={value} set={set}/>;else if(item.family==="BDA"||item.family==="RRE")fields=<Strip options={options} value={value} set={set}/>;else if(item.family==="FSR"||item.family==="RSR")fields=<Rank options={options} value={value} set={set}/>;else if(item.family==="RMX")fields=<Matrix options={options} value={value} set={set}/>;else if(item.family==="PCR")fields=<Pace options={options} value={value} set={set}/>;else if(item.family==="PIS")fields=<Sort options={options} value={value} set={set}/>;else if(item.family==="FCF")fields=<Fit options={options} value={value} set={set}/>;else fields=<Choices options={options} value={value} set={set} label={item.family==="RL"?"Who or what role should stay in view?":"Choose any that fit, or add your own."}/>;return <>{fields}<SafetyContext item={item} value={value} set={set}/></>}
type Props={options:RenderedOption[];value:Record<string,unknown>;set:(key:string,v:unknown)=>void};
function Choices({options,value,set,label}:Props&{label:string}){const chosen=Array.isArray(value.choices)?value.choices as string[]:[];return <fieldset><legend>{label}</legend><div className={styles.options}>{options.map(x=><button type="button" key={x.id} className={chosen.includes(x.id)?styles.selected:styles.option} aria-pressed={chosen.includes(x.id)} onClick={()=>set("choices",chosen.includes(x.id)?chosen.filter(v=>v!==x.id):[...chosen,x.id])}>{x.label}</button>)}</div><label className={styles.field}>Private note (optional; encrypted and excluded from report generation)<textarea value={String(value.note??"")} onChange={e=>set("note",e.target.value)}/></label></fieldset>}
function Strip({options,value,set}:Props){return <fieldset><legend>Fill only the parts you remember</legend><div className={styles.strip}>{["Before","When it first hit","What happened next","Later / aftermath"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}><option value="">Leave blank</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}</div></fieldset>}
function Rank({options,value,set}:Props){const rank=Array.isArray(value.rank)?value.rank as string[]:[];return <fieldset><legend>Choose in the order they arrive. Buttons work as a drag-free alternative.</legend><div className={styles.options}>{options.map(x=><button type="button" key={x.id} className={rank.includes(x.id)?styles.selected:styles.option} onClick={()=>set("rank",rank.includes(x.id)?rank.filter(v=>v!==x.id):[...rank,x.id])}>{rank.includes(x.id)?`${rank.indexOf(x.id)+1}. `:""}{x.label}</button>)}</div></fieldset>}
function Body({options,value,set}:Props){const active=Array.isArray(value.zones)?value.zones as string[]:[];return <fieldset><legend>Where, if anywhere, changed? Choose only the authored descriptions that fit.</legend><div className={styles.body}><div aria-hidden="true" className={styles.silhouette}>●<br/>│<br/>◯<br/>│<br/>╱ ╲</div><div className={styles.options}>{options.map(x=><button type="button" key={x.id} className={active.includes(x.id)?styles.selected:styles.option} aria-pressed={active.includes(x.id)} onClick={()=>set("zones",active.includes(x.id)?active.filter(v=>v!==x.id):[...active,x.id])}>{x.label}</button>)}</div></div></fieldset>}
function Matrix({options,value,set}:Props){return <fieldset><legend>Answer each row separately. Differences are useful.</legend><div className={styles.matrix}>{["Person / role 1","Person / role 2"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}><option value="">Not applicable / no memory</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}</div></fieldset>}
function Pace({options,value,set}:Props){const bands=options.filter((option)=>/^(?:not applicable|too fast|workable band|too slow|changes by (?:state\/)?context|cannot quantify)$/iu.test(option.label));return <fieldset><legend>Mark only the kinds of closeness that matter here.</legend><div className={styles.matrix}>{["Contact frequency","Emotional disclosure","Asking for help","Space"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}><option value="">Leave blank</option>{bands.map(band=><option key={band.id} value={band.id}>{band.label}</option>)}</select></label>)}</div></fieldset>}
function Sort({options,value,set}:Props){const relations=options.filter((option)=>/same internal presence|same family|different but allied|opponents|one follows|genuinely different|one card does not match|not enough access/iu.test(option.label));return <><Choices options={options} value={value} set={set} label="Tap to group working descriptions. You can revise or leave them separate."/><Choices options={relations} value={{choices:value.relationship??[]}} set={(_,v)=>set("relationship",v)} label="How do they fit, if at all?"/></>}
function Fit({options,value,set}:Props){const fitOptions=options.filter((option)=>/^(?:matches|close—edit|fits only when…|does not match|not enough evidence|do not include)$/iu.test(option.label));return <fieldset><legend>Nothing is included without your say-so.</legend><Choices options={fitOptions} value={value} set={set} label="For this working description…"/><label className={styles.check}><input type="checkbox" checked={value.quotePermission===true} onChange={e=>set("quotePermission",e.target.checked)}/>You may quote my edited words. Otherwise they remain a paraphrase.</label></fieldset>}
function SafetyContext({item,value,set}:{item:RenderedInteraction;value:Record<string,unknown>;set:(k:string,v:unknown)=>void}){return <fieldset><legend>Context and pacing (optional)</legend><label>Context safety<select value={String(value.safetyContext??"unknown")} onChange={e=>set("safetyContext",e.target.value)}><option value="unknown">Prefer not to say / unknown</option><option value="safe">Generally safe</option><option value="mixed">Mixed or unstable</option><option value="unsafe">Threatening, coercive, or unsafe</option></select></label><label>Activation<select value={String(value.userArousal??"unknown")} onChange={e=>set("userArousal",e.target.value)}><option value="unknown">Not sure</option><option value="low">Low</option><option value="elevated">Elevated</option><option value="high">High / too much</option></select></label>{(item.family==="RSR"||item.family==="SEF")&&<label className={styles.check}><input type="checkbox" checked={value.resourceSafetyClear===true} onChange={e=>set("resourceSafetyClear",e.target.checked)}/>I am ready to leave the safety/resource step.</label>}</fieldset>}
function Pause({state,request}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>)=>void}){return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>Your pace is welcome here</p><h1>We saved your place.</h1><p>{state.resumeCue??"You can return to a lower-demand question when it feels right."}</p><div className={styles.grounding}><h2>A quick reset, if useful</h2><p>Notice your feet, the chair supporting you, and one ordinary object in the room. You do not need to focus on your breath.</p></div><button className={styles.primary} onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"resume"})}>Continue gently</button></section></main>}
function Generating({state,pass,poll}:{state:AssessmentState;pass:1|2;poll:()=>void}){useEffect(()=>{const timer=window.setInterval(poll,2500);return()=>window.clearInterval(timer)},[poll]);return <main className={styles.shell}><section className={styles.intro} aria-live="polite"><p className={styles.kicker}>Patternwork</p><h1>Preparing your {pass===1?"mapping summary":"report"}.</h1><p>Your answers are saved. You can leave this page and return using your private link.</p>{state.deliveryStatus==="FAILED"?<p className={styles.small}>We could not send the “report started” email, but preparation is still continuing here.</p>:null}</section></main>}
function ReportFailure({state,reload}:{state:AssessmentState;reload:()=>void}){
 const [message,setMessage]=useState(""),[retrying,setRetrying]=useState(false);
 const retry=async()=>{setRetrying(true);setMessage("");try{const r=await fetch("/api/reports/retry",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()}});if(!r.ok)throw Error();setMessage("Your report has been queued again.");await reload()}catch{setMessage("We could not restart preparation. Please try again later.")}finally{setRetrying(false)}};
 const userRetry=state.canRetry&&state.retryAudience==="USER";
 return <main className={styles.shell}><section className={styles.intro} aria-live="polite"><p className={styles.kicker}>Patternwork</p><h1>We could not finish preparing your report.</h1><p>Your answers are still saved and no partial report has been released. You can return using your private link.</p>{state.deliveryStatus==="FAILED"?<p>We also could not send the report-status email. Your saved assessment and retry options remain available here.</p>:null}{userRetry?<button className={styles.primary} type="button" disabled={retrying} onClick={()=>void retry()}>{retrying?"Retrying…":"Try again"}</button>:<p className={styles.small}>This needs a secure review before it can be retried. You do not need to retake the assessment.</p>}{message?<p className={styles.error} role="status">{message}</p>:null}</section></main>;
}
function Boundary({state,request}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>)=>void}){
 const ready=state.status==="report_ready",summaryReady=state.status==="pass1_ready",pass=state.pass===1?1:2,awaitingFreeze=Boolean(state.canCompletePass)&&state.reportStatus==="NOT_STARTED";
 const [selectedTopics,setSelectedTopics]=useState<string[]>(state.optedInTopics??[]);
 const [focusOccurrenceRefs,setFocusOccurrenceRefs]=useState<string[]>([]);
 const [detailPermissions,setDetailPermissions]=useState<string[]>([]);
 const [comparisonFirstRef,setComparisonFirstRef]=useState("");
 const [comparisonSecondRef,setComparisonSecondRef]=useState("");
 const [comparisonRelation,setComparisonRelation]=useState<Pwqe51ComparisonRelation|"">("");
 const isPwqe51Pass1=state.engine==="PWQE51"&&pass===1;
 const complete=(action:"finish"|"continue"|"end")=>request("complete-pass","POST",{
  expectedRevision:state.revision,completedPass:pass,action,
  ...(pass===1&&action==="continue"?{optedInTopics:selectedTopics}:{}),
  ...(isPwqe51Pass1&&action==="continue"?buildPwqe51DeepeningPreferences({focuses:state.availableFocuses??[],focusOccurrenceRefs,detailPermissions,comparisonFirstRef,comparisonSecondRef,...(comparisonRelation?{comparisonRelation}:{})}):{}),
 });
 const reportUrl=state.reportReadyUrl??(state.assessmentId?`/reports/${state.assessmentId}`:"#");
 if(awaitingFreeze)return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>This pass is complete</p><h1>{pass===1?"Ready to prepare your Mapping Summary.":"Ready to prepare your full reports."}</h1><p>{state.reportUnavailable?"Your answers are saved, but report preparation is temporarily unavailable. You can try again later without retaking the assessment.":"Your answers are saved. Report generation starts only after you choose to continue."}</p>
  {pass===1&&<fieldset><legend>Choose any topics you want to explore in the optional Deepening pass.</legend>{(state.availableTopics??[]).map((topic)=><label className={styles.check} key={topic.id}><input type="checkbox" checked={selectedTopics.includes(topic.id)} onChange={(event)=>setSelectedTopics(event.target.checked?[...selectedTopics,topic.id]:selectedTopics.filter((id)=>id!==topic.id))}/><span><strong>{topic.label}</strong>{topic.description&&<span> — {topic.description}</span>}</span></label>)}</fieldset>}
  {isPwqe51Pass1&&<Pwqe51DeepeningPreferences state={state} focusOccurrenceRefs={focusOccurrenceRefs} setFocusOccurrenceRefs={setFocusOccurrenceRefs} detailPermissions={detailPermissions} setDetailPermissions={setDetailPermissions} comparisonFirstRef={comparisonFirstRef} setComparisonFirstRef={setComparisonFirstRef} comparisonSecondRef={comparisonSecondRef} setComparisonSecondRef={setComparisonSecondRef} comparisonRelation={comparisonRelation} setComparisonRelation={setComparisonRelation}/>}
  <button className={styles.primary} onClick={()=>complete("continue")}>{state.reportUnavailable?"Check availability again":pass===1?"Generate Mapping Summary":"Prepare full reports"}</button>{pass===1&&<button className={styles.textButton} onClick={()=>complete("end")}>End now with what is supported</button>}</section></main>;
 return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>{summaryReady?"First pass saved":"Patternwork"}</p><h1>{ready?"Your report is ready.":summaryReady?"You have a supported Mapping Summary.":"Your deeper pass is complete."}</h1><p>{ready?"Open your private report when you’re ready.":"This reflects only what is supported by your answers. You can continue or finish here."}</p>{ready&&state.deliveryStatus==="FAILED"?<p className={styles.small}>The report is available here, but we could not send its email notification.</p>:null}{ready?<a className={styles.primary} href={reportUrl}>Open report</a>:<>{summaryReady&&state.mappingSummaryUrl&&<a className={styles.primary} href={state.mappingSummaryUrl}>Open Mapping Summary</a>}{isPwqe51Pass1&&<Pwqe51DeepeningPreferences state={state} focusOccurrenceRefs={focusOccurrenceRefs} setFocusOccurrenceRefs={setFocusOccurrenceRefs} detailPermissions={detailPermissions} setDetailPermissions={setDetailPermissions} comparisonFirstRef={comparisonFirstRef} setComparisonFirstRef={setComparisonFirstRef} comparisonSecondRef={comparisonSecondRef} setComparisonSecondRef={setComparisonSecondRef} comparisonRelation={comparisonRelation} setComparisonRelation={setComparisonRelation}/>}<button className={styles.primary} onClick={()=>complete("continue")}>{summaryReady?"Continue to an optional deeper pass":"Prepare reports"}</button><button className={styles.textButton} onClick={()=>complete("end")}>Finish with what is already supported</button></>}</section></main>
}
function Pwqe51DeepeningPreferences({state,focusOccurrenceRefs,setFocusOccurrenceRefs,detailPermissions,setDetailPermissions,comparisonFirstRef,setComparisonFirstRef,comparisonSecondRef,setComparisonSecondRef,comparisonRelation,setComparisonRelation}:{state:AssessmentState;focusOccurrenceRefs:string[];setFocusOccurrenceRefs:(value:string[])=>void;detailPermissions:string[];setDetailPermissions:(value:string[])=>void;comparisonFirstRef:string;setComparisonFirstRef:(value:string)=>void;comparisonSecondRef:string;setComparisonSecondRef:(value:string)=>void;comparisonRelation:Pwqe51ComparisonRelation|"";setComparisonRelation:(value:Pwqe51ComparisonRelation|"")=>void}){
 const focuses=state.availableFocuses??[];
 return <>
  <fieldset><legend>Choose any remembered occasions you would like to explore more closely.</legend>{focuses.length?focuses.map((focus)=><label className={styles.check} key={focus.ref}><input type="checkbox" checked={focusOccurrenceRefs.includes(focus.ref)} onChange={(event)=>setFocusOccurrenceRefs(event.target.checked?[...focusOccurrenceRefs,focus.ref]:focusOccurrenceRefs.filter((ref)=>ref!==focus.ref))}/><span>{focus.label}</span></label>):<p className={styles.small}>There are no specific recalled occasions available to select right now.</p>}</fieldset>
  <fieldset><legend>What would you like to look at more closely? Choose any that interest you.</legend>{PWQE51_DETAIL_PERMISSIONS.map((permission)=><label className={styles.check} key={permission.id}><input type="checkbox" checked={detailPermissions.includes(permission.id)} onChange={(event)=>setDetailPermissions(event.target.checked?[...detailPermissions,permission.id]:detailPermissions.filter((id)=>id!==permission.id))}/><span>{permission.label}</span></label>)}</fieldset>
  {focuses.length>1&&<fieldset><legend>Are these two remembered occasions different, the same, or are you unsure?</legend>
   <label>First occasion<select value={comparisonFirstRef} onChange={(event)=>{const next=event.target.value;setComparisonFirstRef(next);if(next===comparisonSecondRef)setComparisonSecondRef("")}}><option value="">Choose an occasion</option>{focuses.map((focus)=><option key={focus.ref} value={focus.ref}>{focus.label}</option>)}</select></label>
   <label>Second occasion<select value={comparisonSecondRef} onChange={(event)=>setComparisonSecondRef(event.target.value)}><option value="">Choose a different occasion</option>{focuses.filter((focus)=>focus.ref!==comparisonFirstRef).map((focus)=><option key={focus.ref} value={focus.ref}>{focus.label}</option>)}</select></label>
   <label>How do they relate?<select aria-label="How do these occasions relate?" value={comparisonRelation} onChange={(event)=>setComparisonRelation(event.target.value as Pwqe51ComparisonRelation|"")}><option value="">Choose one</option><option value="different">Different occasions</option><option value="same">The same occasion</option><option value="cannot_tell">I cannot tell</option></select></label>
   <p className={styles.small}>Choose “Different occasions” only when you know these refer to separate moments. “The same occasion” and “I cannot tell” remain distinct choices.</p>
  </fieldset>}
 </>;
}
function Recovery({retry,preview}:{retry:()=>void;preview:()=>void}){return <main className={styles.shell}><section className={styles.intro}><h1>We can’t reach your saved session right now.</h1><p>No new answers have been recorded. Try again, or view a non-saving development preview.</p><button className={styles.primary} onClick={retry}>Try again</button><button className={styles.textButton} onClick={preview}>View preview</button></section></main>}
