"use client";
/* eslint-disable react-hooks/exhaustive-deps -- autosave intentionally keys off serialized draft and authoritative revision */
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import styles from "./assessment.module.css";
import { buildTypedAssessmentResponse, familyLabel, normaliseAssessmentState, responseOrderForDraft, semanticOptionId, stateForHttpStatus, type AssessmentState, type RenderedInteraction, type RenderedOption } from "./ui-state";

const API="/api/assessment";
const previewItem: RenderedInteraction={instanceId:"preview-RL-101",bankItemId:"RL-101",family:"RL",stage:"S0",prompt:"People and roles to use today",helpText:"Choose the option that is easiest to answer today.",options:["A close friend","A family member","A partner or dating person","Another important person","No one fits right now"].map((label)=>({id:semanticOptionId("preview-RL-101",label),label}))};

export default function AssessmentPage(){
 const [state,setState]=useState<AssessmentState|null>(null),[failed,setFailed]=useState(false),[save,setSave]=useState(""),[preview,setPreview]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch(`${API}/state`,{cache:"no-store"});const unauthenticated=stateForHttpStatus(r.status);if(unauthenticated){setState(unauthenticated);setFailed(false);return}if(!r.ok)throw Error();setState(normaliseAssessmentState(await r.json()));setFailed(false)}catch{setFailed(true)}},[]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const request=useCallback(async(path:string,method:"POST"|"PUT",body:Record<string,unknown>,headers:Record<string,string>={})=>{if(!state||preview){setSave("Preview mode is not saved.");return}setSave("Saving…");try{const r=await fetch(`${API}/${path}`,{method,headers:{"Content-Type":"application/json",...headers},body:JSON.stringify(body)});if(r.status===409){setSave("Updated elsewhere — showing latest saved version.");return void load()}if(!r.ok)throw Error();setState(normaliseAssessmentState(await r.json()));setSave("Saved")}catch{setSave("Could not save. Please try again.")}},[load,preview,state]);
 if(!state&&!failed)return <main className={styles.shell}><p className={styles.loading}>Preparing your private session…</p></main>;
 if(!state)return <Recovery retry={load} preview={()=>{setPreview(true);setState({status:"active",interaction:previewItem,mode:"preview"})}}/>;
 if(state.status==="needs_consent")return <Consent email={state.email} start={(email)=>request("start","POST",{email,consentVersion:"PWQE3-CONSENT-1"})} preview={()=>{setPreview(true);setState({status:"active",interaction:previewItem,mode:"preview"})}}/>;
 if(state.status==="generating_pass1"||state.status==="generating_pass2")return <Generating pass={state.status.endsWith("pass1")?1:2} poll={load}/>;
 if(state.status==="pass1_ready"||state.status==="pass2_ready"||state.status==="report_ready")return <Boundary state={state} request={request}/>;
 if(state.status==="paused"||state.status==="recovery")return <Pause state={state} request={request}/>;
 if(state.interaction===null&&state.canCompletePass)return <Boundary state={state} request={request}/>;
 return <Question key={state.interaction?.instanceId??"preview"} state={state} request={request} save={save} preview={preview}/>;
}
function Consent({email,start,preview}:{email?:string;start:(email:string)=>void;preview:()=>void}){const [value,setValue]=useState(email??""),[ok,setOk]=useState(false),[error,setError]=useState("");function submit(e:FormEvent){e.preventDefault();if(!ok)return setError("Please confirm before continuing.");if(!/^\S+@\S+\.\S+$/.test(value))return setError("Enter an email address for your private resume link.");start(value.trim())}return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>Patternwork · private reflection</p><h1>A guided map of patterns that matter to you.</h1><p>This is not therapy, diagnosis, medical care, or an assessment of another person. You control what you share, may skip any prompt, and can pause whenever you need.</p><p>Selected options are categories, not your exact words.</p><form className={styles.form} onSubmit={submit}><label>Email for your private resume link<input type="email" value={value} onChange={e=>setValue(e.target.value)} required autoComplete="email"/></label><label className={styles.check}><input type="checkbox" checked={ok} onChange={e=>setOk(e.target.checked)}/>I understand this is a non-diagnostic reflection tool and I may pause, skip, or stop.</label>{error&&<p role="alert" className={styles.error}>{error}</p>}<button className={styles.primary}>Begin when ready</button></form><button className={styles.textButton} type="button" onClick={preview}>View the static test without saving</button><p className={styles.small}>If you feel in immediate danger or unable to stay safe, pause this tool and contact local emergency or crisis support.</p></section></main>}
function Question({state,request,save,preview}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>,h?:Record<string,string>)=>void;save:string;preview:boolean}){const item=state.interaction??previewItem;const initialDraft=state.draft??{};const [value,setValue]=useState<Record<string,unknown>>(()=>initialDraft),lastSaved=useRef(JSON.stringify(initialDraft));const responseHeaders=()=>({"Idempotency-Key":crypto.randomUUID()});const payload=(completionState:"PARTIAL"|"COMPLETED"|"SKIPPED")=>({expectedRevision:state.revision,interactionInstanceId:item.instanceId,bankItemId:item.bankItemId,completionState,response:buildTypedAssessmentResponse(item,value),responseOrder:responseOrderForDraft(value)});useEffect(()=>{const serialized=JSON.stringify(value);if(preview||!Object.keys(value).length||serialized===lastSaved.current)return;const timer=window.setTimeout(()=>{lastSaved.current=serialized;request("response","PUT",payload("PARTIAL"),responseHeaders())},700);return()=>window.clearTimeout(timer)},[item.bankItemId,item.instanceId,preview,request,state.revision,value]);const send=(completionState:"COMPLETED"|"SKIPPED")=>request("response","PUT",payload(completionState),responseHeaders());return <main className={styles.shell}><header className={styles.header}><div><p className={styles.kicker}>Patternwork · {state.stageLabel??`Stage ${item.stage.slice(1)}`}</p><p className={styles.progressText}>You’re moving through a few areas, at your own pace.</p>{state.mappingSummaryUrl&&<a href={state.mappingSummaryUrl}>Open your Mapping Summary</a>}</div><p className={styles.save} aria-live="polite">{preview?"Preview — not saved":save||"Saved automatically"}</p></header><div className={styles.stageBar} aria-label="Stage progress"><span style={{width:`${Math.max(8,Math.min(100,state.stageProgress??8))}%`}}/></div><section className={styles.card} aria-labelledby="prompt"><p className={styles.family}>{familyLabel(item.family)} <span>· optional detail</span></p><h1 id="prompt">{item.prompt}</h1>{item.helpText&&<p className={styles.help}>{item.helpText}</p>}<Renderer item={item} value={value} setValue={setValue}/><div className={styles.controls}><button className={styles.textButton} onClick={()=>send("SKIPPED")}>Skip</button><button className={styles.textButton} onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"pause"})}>Pause & save</button><button className={styles.primary} onClick={()=>send("COMPLETED")}>Continue</button></div><p className={styles.small}>“Not sure,” “none fit,” and “it depends” are useful answers.</p></section></main>}
function Renderer({item,value,setValue}:{item:RenderedInteraction;value:Record<string,unknown>;setValue:(v:Record<string,unknown>)=>void}){const set=(key:string,v:unknown)=>setValue({...value,[key]:v}),options=item.options?.length?item.options:["Not sure","None fit","It depends on the person","Something else"].map((label)=>({id:semanticOptionId(`${item.bankItemId}-fallback`,label),label}));let fields;if(item.family==="BTM")fields=<Body value={value} set={set}/>;else if(item.family==="BDA"||item.family==="RRE")fields=<Strip options={options} value={value} set={set}/>;else if(item.family==="FSR"||item.family==="RSR")fields=<Rank options={options} value={value} set={set}/>;else if(item.family==="RMX")fields=<Matrix options={options} value={value} set={set}/>;else if(item.family==="PCR")fields=<Pace value={value} set={set}/>;else if(item.family==="PIS")fields=<Sort options={options} value={value} set={set}/>;else if(item.family==="FCF")fields=<Fit value={value} set={set}/>;else fields=<Choices options={options} value={value} set={set} label={item.family==="RL"?"Who or what role should stay in view?":"Choose any that fit, or add your own."}/>;return <>{fields}<SafetyContext item={item} value={value} set={set}/></>}
type Props={options:RenderedOption[];value:Record<string,unknown>;set:(key:string,v:unknown)=>void};
function Choices({options,value,set,label}:Props&{label:string}){const chosen=Array.isArray(value.choices)?value.choices as string[]:[];return <fieldset><legend>{label}</legend><div className={styles.options}>{options.map(x=><button type="button" key={x.id} className={chosen.includes(x.id)?styles.selected:styles.option} aria-pressed={chosen.includes(x.id)} onClick={()=>set("choices",chosen.includes(x.id)?chosen.filter(v=>v!==x.id):[...chosen,x.id])}>{x.label}</button>)}</div><label className={styles.field}>Private note (optional; encrypted and excluded from report generation)<textarea value={String(value.note??"")} onChange={e=>set("note",e.target.value)}/></label></fieldset>}
function Strip({options,value,set}:Props){return <fieldset><legend>Fill only the parts you remember</legend><div className={styles.strip}>{["Before","When it first hit","What happened next","Later / aftermath"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}><option value="">Leave blank</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}</div></fieldset>}
function Rank({options,value,set}:Props){const rank=Array.isArray(value.rank)?value.rank as string[]:[];return <fieldset><legend>Choose in the order they arrive. Buttons work as a drag-free alternative.</legend><div className={styles.options}>{options.map(x=><button type="button" key={x.id} className={rank.includes(x.id)?styles.selected:styles.option} onClick={()=>set("rank",rank.includes(x.id)?rank.filter(v=>v!==x.id):[...rank,x.id])}>{rank.includes(x.id)?`${rank.indexOf(x.id)+1}. `:""}{x.label}</button>)}</div></fieldset>}
function Body({value,set}:{value:Record<string,unknown>;set:(k:string,v:unknown)=>void}){const zones=["Face/head","Throat","Chest","Belly","Hands/arms","Legs/feet","Whole body","No clear body signal"].map(label=>({id:semanticOptionId("body-zone",label),label})),active=Array.isArray(value.zones)?value.zones as string[]:[];return <fieldset><legend>Where, if anywhere, changed? The list is a full keyboard alternative to the body picture.</legend><div className={styles.body}><div aria-hidden="true" className={styles.silhouette}>●<br/>│<br/>◯<br/>│<br/>╱ ╲</div><div className={styles.options}>{zones.map(x=><button type="button" key={x.id} className={active.includes(x.id)?styles.selected:styles.option} aria-pressed={active.includes(x.id)} onClick={()=>set("zones",active.includes(x.id)?active.filter(v=>v!==x.id):[...active,x.id])}>{x.label}</button>)}</div></div></fieldset>}
function Matrix({options,value,set}:Props){return <fieldset><legend>Answer each row separately. Differences are useful.</legend><div className={styles.matrix}>{["Person / role 1","Person / role 2"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}><option value="">Not applicable / no memory</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label>)}</div></fieldset>}
function Pace({value,set}:{value:Record<string,unknown>;set:(k:string,v:unknown)=>void}){const bands=["Not applicable","Too fast","Workable band","Too slow","Changes by context"].map(label=>({id:semanticOptionId("pace-band",label),label}));return <fieldset><legend>Mark only the kinds of closeness that matter here.</legend><div className={styles.matrix}>{["Contact frequency","Emotional disclosure","Asking for help","Space"].map(x=><label key={x}>{x}<select value={String(value[x]??"")} onChange={e=>set(x,e.target.value)}>{bands.map(band=><option key={band.id} value={band.id}>{band.label}</option>)}</select></label>)}</div></fieldset>}
function Sort({options,value,set}:Props){return <><Choices options={options} value={value} set={set} label="Tap to group working descriptions. You can revise or leave them separate."/><Choices options={["Same pattern","Same family, different versions","Different but allied","Opponents","Genuinely different","Not enough access"].map((label)=>({id:semanticOptionId("pattern-relation",label),label}))} value={{choices:value.relationship??[]}} set={(_,v)=>set("relationship",v)} label="How do they fit, if at all?"/></>}
function Fit({value,set}:{value:Record<string,unknown>;set:(k:string,v:unknown)=>void}){return <fieldset><legend>Nothing is included without your say-so.</legend><Choices options={["Matches","Close — edit","Fits only when…","Does not match","Not enough evidence","Do not include"].map((label)=>({id:semanticOptionId("fit",label),label}))} value={value} set={set} label="For this working description…"/><label className={styles.check}><input type="checkbox" checked={value.quotePermission===true} onChange={e=>set("quotePermission",e.target.checked)}/>You may quote my edited words. Otherwise they remain a paraphrase.</label></fieldset>}
function SafetyContext({item,value,set}:{item:RenderedInteraction;value:Record<string,unknown>;set:(k:string,v:unknown)=>void}){return <fieldset><legend>Context and pacing (optional)</legend><label>Context safety<select value={String(value.safetyContext??"unknown")} onChange={e=>set("safetyContext",e.target.value)}><option value="unknown">Prefer not to say / unknown</option><option value="safe">Generally safe</option><option value="mixed">Mixed or unstable</option><option value="unsafe">Threatening, coercive, or unsafe</option></select></label><label>Activation<select value={String(value.userArousal??"unknown")} onChange={e=>set("userArousal",e.target.value)}><option value="unknown">Not sure</option><option value="low">Low</option><option value="elevated">Elevated</option><option value="high">High / too much</option></select></label>{(item.family==="RSR"||item.family==="SEF")&&<label className={styles.check}><input type="checkbox" checked={value.resourceSafetyClear===true} onChange={e=>set("resourceSafetyClear",e.target.checked)}/>I am ready to leave the safety/resource step.</label>}</fieldset>}
function Pause({state,request}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>)=>void}){return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>Your pace is welcome here</p><h1>We saved your place.</h1><p>{state.resumeCue??"You can return to a lower-demand question when it feels right."}</p><div className={styles.grounding}><h2>A quick reset, if useful</h2><p>Notice your feet, the chair supporting you, and one ordinary object in the room. You do not need to focus on your breath.</p></div><button className={styles.primary} onClick={()=>request("pause","POST",{expectedRevision:state.revision,action:"resume"})}>Continue gently</button></section></main>}
function Generating({pass,poll}:{pass:1|2;poll:()=>void}){useEffect(()=>{const timer=window.setInterval(poll,2500);return()=>window.clearInterval(timer)},[poll]);return <main className={styles.shell}><section className={styles.intro} aria-live="polite"><p className={styles.kicker}>Patternwork</p><h1>Preparing your {pass===1?"mapping summary":"report"}.</h1><p>Your answers are saved. You can leave this page and return using your private link.</p></section></main>}
function Boundary({state,request}:{state:AssessmentState;request:(p:string,m:"POST"|"PUT",b:Record<string,unknown>)=>void}){
 const ready=state.status==="report_ready",summaryReady=state.status==="pass1_ready",pass=state.pass===1?1:2,awaitingFreeze=Boolean(state.canCompletePass)&&state.reportStatus==="NOT_STARTED";
 const complete=(action:"finish"|"continue")=>request("complete-pass","POST",{expectedRevision:state.revision,completedPass:pass,action});
 const reportUrl=state.reportReadyUrl??(state.assessmentId?`/reports/${state.assessmentId}`:"#");
 if(awaitingFreeze)return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>This pass is complete</p><h1>{pass===1?"Ready to prepare your Mapping Summary.":"Ready to prepare your full reports."}</h1><p>Your answers are saved. Report generation starts only after you choose to continue.</p><button className={styles.primary} onClick={()=>complete("continue")}>{pass===1?"Generate Mapping Summary":"Prepare full reports"}</button></section></main>;
 return <main className={styles.shell}><section className={styles.intro}><p className={styles.kicker}>{summaryReady?"First pass saved":"Patternwork"}</p><h1>{ready?"Your report is ready.":summaryReady?"You have a supported Mapping Summary.":"Your deeper pass is complete."}</h1><p>{ready?"Open your private report when you’re ready.":"This reflects only what is supported by your answers. You can continue or finish here."}</p>{ready?<a className={styles.primary} href={reportUrl}>Open report</a>:<>{summaryReady&&state.mappingSummaryUrl&&<a className={styles.primary} href={state.mappingSummaryUrl}>Open Mapping Summary</a>}<button className={styles.primary} onClick={()=>complete("continue")}>{summaryReady?"Continue to an optional deeper pass":"Prepare reports"}</button><button className={styles.textButton} onClick={()=>complete("finish")}>Finish with what is already supported</button></>}</section></main>
}
function Recovery({retry,preview}:{retry:()=>void;preview:()=>void}){return <main className={styles.shell}><section className={styles.intro}><h1>We can’t reach your saved session right now.</h1><p>No new answers have been recorded. Try again, or view a non-saving development preview.</p><button className={styles.primary} onClick={retry}>Try again</button><button className={styles.textButton} onClick={preview}>View preview</button></section></main>}
