export type AnswerType = "T1" | "T2" | "T3" | "T4" | "T5" | "T6";

export type Option = { id: string; text: string };

type BaseQuestion = {
  num: number;
  text: string;
  answerType: AnswerType;
};

export type QuestionData =
  | (BaseQuestion & { answerType: "T1"; tap1: Option[]; tap2: Option[] })
  | (BaseQuestion & { answerType: "T2"; options: Option[] })
  | (BaseQuestion & { answerType: "T3"; options: [Option, Option] })
  | (BaseQuestion & { answerType: "T4"; options: Option[] })
  | (BaseQuestion & { answerType: "T5"; leftLabel: string; rightLabel: string })
  | (BaseQuestion & { answerType: "T6"; options: Option[] });

const o = (id: string, text: string): Option => ({ id, text });

export const QUESTIONS: QuestionData[] = [
  { num: 1, answerType: "T1", text: "Tomorrow morning you have to walk into a room and present something you made to people whose opinion actually matters to you. Tonight you're supposed to be sleeping.", tap1: [o("A", "slides on loop"), o("B", "body won't settle"), o("C", "pretending tomorrow isn't happening"), o("D", "telling myself it's not that big a deal")], tap2: [o("A", "rehearsing every question"), o("B", "scrolling to not be alone with it"), o("C", "I'll wing it"), o("D", "already planning my recovery if it bombs")] },
  { num: 2, answerType: "T2", text: "Your boss — or someone whose approval you actually need — just told you the thing you worked hard on isn't good enough. You're still sitting across from them.", options: [o("A", "defending before they finish"), o("B", "nodding and going blank"), o("C", "agreeing faster than I actually agree"), o("D", "fighting tears")] },
  { num: 3, answerType: "T3", text: "You've been seeing someone for a few months and it's actually going well.", options: [o("A", "I keep waiting for the moment it stops"), o("B", "I keep noticing things about them that bother me")] },
  { num: 4, answerType: "T1", text: "You and your partner (or your closest person) had a real fight last night. You're driving to work alone this morning.", tap1: [o("A", "running it on a loop"), o("B", "hollowed out and quiet"), o("C", "building my case"), o("D", "can barely remember what it was about")], tap2: [o("A", "I'll text first, I can't stand this"), o("B", "I'll wait and see if they reach out"), o("C", "I want to talk to someone else first"), o("D", "I want to act like it didn't happen tonight")] },
  { num: 5, answerType: "T2", text: "You're at your parents' house for a holiday. Your mom (or whoever raised you) says the thing she always says — the one that's been getting under your skin since you were a teenager.", options: [o("A", "snap back before I can stop"), o("B", "leave the room"), o("C", "smile and change the subject"), o("D", "feel twelve again and just take it")] },
  { num: 6, answerType: "T3", text: "You and your partner just had a moment that felt really close — physically, emotionally, both. A few minutes pass.", options: [o("A", "want to keep being in it, scared they're already pulling away"), o("B", "ready to be in my own head, the closeness is starting to feel like a lot")] },
  { num: 7, answerType: "T1", text: "End of the month, you just looked at your bank account and it's lower than you thought. Phone in your hand.", tap1: [o("A", "chest tight and stays tight"), o("B", "a familiar dread"), o("C", "numb, put the phone down"), o("D", "immediately doing math")], tap2: [o("A", "make a plan, feel a little better"), o("B", "close the app, try not to think"), o("C", "blaming myself for things I bought"), o("D", "texting someone for reassurance")] },
  { num: 8, answerType: "T2", text: "A friend you actually care about just accused you of something you didn't do — or got your motive wrong in a way that really stings.", options: [o("A", "explaining myself fast"), o("B", "something closes down inside me"), o("C", "get angry and let them know"), o("D", "want to walk away and not come back")] },
  { num: 9, answerType: "T5", text: "When someone you care about is upset with you and you can tell they want to talk about it:", leftLabel: "fix it right now, can't stand the gap", rightLabel: "need a lot of time before I can be in the same room" },
  { num: 10, answerType: "T6", text: "After something hard hits — a fight with someone you love, or news you weren't ready for — drag these in the order you actually reach for them:", options: [o("A", "alone somewhere quiet"), o("B", "talking to a specific person who gets it"), o("C", "doing something with my hands or body"), o("D", "getting into a task or screen until it passes")] },
  { num: 11, answerType: "T2", text: "You wake up on a Saturday with nothing you have to do. First thing you notice:", options: [o("A", "my mind goes straight to the list"), o("B", "I feel a kind of empty I don't love"), o("C", "I feel good and don't want to ruin it by thinking"), o("D", "I'm already reaching for my phone")] },
  { num: 12, answerType: "T1", text: "Your closest friend has been distant for about two weeks. You don't know why. You're staring at the thread.", tap1: [o("A", "my stomach has been off for days"), o("B", "I keep telling myself it's nothing"), o("C", "I'm rehearsing what I did wrong"), o("D", "I went numb about it a while ago")], tap2: [o("A", "I'll send something light to test the water"), o("B", "I'll wait for them to come to me"), o("C", "I'm pulling back first so it hurts less"), o("D", "I'll pretend I haven't noticed")] },
  { num: 13, answerType: "T2", text: "You're getting dressed for something you actually want to go to and you catch yourself in the mirror.", options: [o("A", "I look away fast"), o("B", "I start picking myself apart out loud in my head"), o("C", "I change the outfit"), o("D", "I tell myself to stop and try to mean it")] },
  { num: 14, answerType: "T3", text: "When you're alone at night with no one to perform for:", options: [o("A", "there's a voice that starts in on me about the day"), o("B", "there's a quiet I can't quite stay in")] },
  { num: 15, answerType: "T1", text: "You actually need help with something — real help, from someone who could give it. You're holding the phone.", tap1: [o("A", "my chest gets tight at the idea"), o("B", "I feel a kind of shame I don't have a name for"), o("C", "I feel fine, this is just logistics"), o("D", "I already know I'm not going to ask")], tap2: [o("A", "I draft it three times and send it"), o("B", "I tell myself I'll handle it alone"), o("C", "I ask but make it sound smaller than it is"), o("D", "I put the phone down and don't come back")] },
  { num: 16, answerType: "T2", text: "Someone in a meeting just took credit for an idea that was yours. The room moved on.", options: [o("A", "I'm replaying it trying to decide if I imagined it"), o("B", "I'm furious and saying nothing"), o("C", "I'll bring it up with them privately later"), o("D", "I'm already letting it go because it's not worth it")] },
  { num: 17, answerType: "T3", text: "Your partner is upset about something and reaches for you in bed.", options: [o("A", "part of me softens and reaches back"), o("B", "part of me freezes and waits for it to pass")] },
  { num: 18, answerType: "T1", text: "You made a mistake at work that other people are going to find out about by tomorrow. You're at home tonight.", tap1: [o("A", "I can't sit still"), o("B", "I feel a sinking I recognize"), o("C", "I'm building the explanation already"), o("D", "I'm in a kind of fog")], tap2: [o("A", "I'm getting ahead of it tonight, telling someone first"), o("B", "I'm hoping it just doesn't come up"), o("C", "I'm rehearsing how to take responsibility cleanly"), o("D", "I'm thinking about whether I can blame the circumstances")] },
  { num: 19, answerType: "T4", text: "Think about the fight with your closest person from item 4, or the most recent real one. Where are you, in relation to that fight, right now?", options: [o("A", "I am in it, there's no space"), o("B", "it's right up against me"), o("C", "I can see it from a little ways off"), o("D", "it's over there and I'm over here"), o("E", "I can barely find it")] },
  { num: 20, answerType: "T2", text: "Something good just happened to you — real recognition, the kind you wanted. You're alone now.", options: [o("A", "I'm already worried it'll get taken away"), o("B", "I feel almost embarrassed by it"), o("C", "I want to tell one specific person right now"), o("D", "I can't quite let it land")] },
  { num: 21, answerType: "T1", text: "Your sibling (or the family member closest to your age) just did the thing they've done your whole life — the one that makes you feel small. Family dinner, you're still at the table.", tap1: [o("A", "I'm hot in the face"), o("B", "I'm going somewhere far away inside"), o("C", "I'm building the comeback"), o("D", "I feel like a kid again")], tap2: [o("A", "I say something sharp"), o("B", "I get quiet for the rest of the meal"), o("C", "I make a joke that has teeth in it"), o("D", "I act like it didn't land")] },
  { num: 22, answerType: "T2", text: "Your partner has been a little off with you for a couple of days and won't say why.", options: [o("A", "I'm asking again even though I told myself I wouldn't"), o("B", "I'm pulling back to match them"), o("C", "I'm being extra warm to fix it"), o("D", "I'm telling myself it's not about me")] },
  { num: 23, answerType: "T3", text: "When someone you've lost comes to mind unexpectedly — a song, a smell, their handwriting:", options: [o("A", "I let it come and it moves through me"), o("B", "I push it down because I can't be in it right now")] },
  { num: 24, answerType: "T1", text: "You said something to your partner yesterday that you know was unfair. They haven't brought it up. You're making coffee this morning.", tap1: [o("A", "it's sitting in my chest"), o("B", "I keep almost forgetting and then remembering"), o("C", "I'm already justifying it to myself"), o("D", "I feel low in a way I can't quite name")], tap2: [o("A", "I'll bring it up before they do"), o("B", "I'll wait to see if they're still upset"), o("C", "I'll do something nice instead of saying it"), o("D", "I'm hoping we can both just move on")] },
  { num: 25, answerType: "T2", text: "Your boss just told you, sincerely, that you're doing great work.", options: [o("A", "I deflect before they finish"), o("B", "I feel warm and let it in"), o("C", "I'm already wondering what they want"), o("D", "I'm waiting for the but")] },
  { num: 26, answerType: "T6", text: "When your closest person is upset with you, drag these in the order they actually happen:", options: [o("A", "I feel it in my body"), o("B", "I start trying to figure out what I did"), o("C", "I do something to fix it or escape it"), o("D", "I tell someone else about it")] },
  { num: 27, answerType: "T2", text: "Your parent (or whoever raised you) is getting older and you noticed something this last visit you can't unsee.", options: [o("A", "I'm pretending I didn't notice"), o("B", "I felt a grief I wasn't ready for"), o("C", "I'm already making a plan"), o("D", "I went somewhere quiet inside")] },
  { num: 28, answerType: "T3", text: "When your partner and your closest friend both need you on the same night:", options: [o("A", "I feel torn and guilty no matter what I pick"), o("B", "I feel a kind of relief at having a reason to choose one")] },
  { num: 29, answerType: "T1", text: "Your partner just said something that sounded like they're rethinking the whole relationship. You're still in the room.", tap1: [o("A", "the floor goes out"), o("B", "I get very calm and very far away"), o("C", "I get hot and ready to fight"), o("D", "I can't feel my body")], tap2: [o("A", "I ask them to say more, even though I'm scared"), o("B", "I shut down and stop talking"), o("C", "I get sharp and protect myself"), o("D", "I leave the room")] },
  { num: 30, answerType: "T2", text: "It's the morning after item 29. They're still asleep next to you.", options: [o("A", "I'm watching them and feel tender"), o("B", "I'm watching them and feel far away"), o("C", "I'm already planning what I'll say when they wake up"), o("D", "I want to leave before they wake up")] },
  { num: 31, answerType: "T2", text: "You're having a normal day and a specific song comes on — one tied to a person or time you don't talk about much.", options: [o("A", "I know exactly what it touched and I let it move"), o("B", "I have no idea why but the floor drops"), o("C", "I change the song fast"), o("D", "I let it play and go somewhere else inside")] },
  { num: 32, answerType: "T1", text: "You reached for your partner last night and they said not tonight. You're brushing your teeth this morning.", tap1: [o("A", "there's a hollow in my chest"), o("B", "I'm fine, it's not a big deal"), o("C", "I'm running through what's wrong with me"), o("D", "I'm already a little angry")], tap2: [o("A", "I'll bring it up gently today"), o("B", "I won't reach for them again for a while"), o("C", "I'll act extra normal so they don't feel bad"), o("D", "I'm pulling back without telling them")] },
  { num: 33, answerType: "T3", text: "When someone you trust really sees something true about you and names it out loud:", options: [o("A", "something in me opens"), o("B", "something in me wants to deflect it fast")] },
  { num: 34, answerType: "T2", text: "Your parent just made it clear, without saying it directly, that they don't approve of a choice you made as an adult.", options: [o("A", "I'm defending the choice harder than I need to"), o("B", "I feel twelve again and small"), o("C", "I change the subject"), o("D", "I let it land and feel the old ache")] },
  { num: 35, answerType: "T1", text: "Your closest person hasn't responded to you in a way that feels longer than usual, and you don't know why. It's been most of a day.", tap1: [o("A", "there's a low alarm under everything I'm doing"), o("B", "I'm telling myself I'm being crazy"), o("C", "I feel cold and far away"), o("D", "my stomach has been off for hours")], tap2: [o("A", "I send another message"), o("B", "I make myself not send anything"), o("C", "I find someone else to be with so I'm not alone with it"), o("D", "I start preparing for the worst")] },
  { num: 36, answerType: "T2", text: "You just got angrier at someone you love than the situation called for. They're looking at you.", options: [o("A", "I'm doubling down because backing off feels worse"), o("B", "I feel sick and I can't say it"), o("C", "I'm already apologizing too much"), o("D", "I'm leaving the room")] },
  { num: 37, answerType: "T3", text: "When you have a whole evening alone with no plans:", options: [o("A", "there's a quiet relief I sink into"), o("B", "there's a restlessness I have to manage")] },
  { num: 38, answerType: "T1", text: "You're getting the sense that your job isn't safe and no one has said it directly. You're driving home.", tap1: [o("A", "I'm running scenarios on a loop"), o("B", "I feel a dread that's older than this job"), o("C", "I'm telling myself I'm imagining it"), o("D", "I feel almost nothing about it")], tap2: [o("A", "I'm updating the resume tonight"), o("B", "I'm waiting to see if I'm wrong"), o("C", "I'm going to bring it up directly tomorrow"), o("D", "I'm checking out emotionally already")] },
  { num: 39, answerType: "T2", text: "A close friend just told you about something great that happened to them — something you've been wanting for yourself.", options: [o("A", "I'm fully happy for them and feel it"), o("B", "I'm performing happiness while something else runs underneath"), o("C", "I feel the comparison and don't like myself for it"), o("D", "I feel a small distance opening up between us")] },
  { num: 40, answerType: "T4", text: "Think about your relationship to your own body right now — not what it looks like, what it feels like to be in it. Where are you?", options: [o("A", "I am my body, no separation"), o("B", "it's right here with me"), o("C", "I notice it from a little ways off"), o("D", "it's something I manage from the outside"), o("E", "I can barely find it")] },
  { num: 41, answerType: "T1", text: "Your partner just apologized for something real, and meant it.", tap1: [o("A", "I feel something in my chest soften"), o("B", "I feel suspicious of it"), o("C", "I feel a wave of sadness I wasn't expecting"), o("D", "I feel nothing and that scares me")], tap2: [o("A", "I tell them it lands and thank them"), o("B", "I make them work for it a little"), o("C", "I forgive too fast to feel it"), o("D", "I accept it but don't let it change anything inside")] },
  { num: 42, answerType: "T2", text: "Someone you love is in real distress and reaching for you. You're the one they called.", options: [o("A", "I drop everything and feel clear"), o("B", "I drop everything and feel a low panic"), o("C", "I help and feel a quiet resentment"), o("D", "I can't quite arrive, even though I'm there")] },
  { num: 43, answerType: "T3", text: "When you know a hard conversation is coming this week:", options: [o("A", "I want to get it over with so it stops living in my body"), o("B", "I want to put it off until I can't anymore")] },
  { num: 44, answerType: "T1", text: "A family event where your sibling is being praised for the thing you've quietly wanted to be praised for. You're standing there with a drink.", tap1: [o("A", "I feel small and hot"), o("B", "I feel a tired old ache"), o("C", "I'm already telling myself I'm above this"), o("D", "I went somewhere far away")], tap2: [o("A", "I add to the praise warmly and mean some of it"), o("B", "I add to it and don't mean it"), o("C", "I get quiet and slip out"), o("D", "I make a joke that points at me instead")] },
  { num: 45, answerType: "T2", text: "Your partner mentioned an ex in passing — nothing dramatic, just a name.", options: [o("A", "I let it pass and barely register it"), o("B", "I feel a small spike I don't show"), o("C", "I ask one too many questions"), o("D", "I go quiet and they notice")] },
  { num: 46, answerType: "T3", text: "When you have nothing to do and no one to talk to and your phone is across the room:", options: [o("A", "I can be with myself and it's mostly okay"), o("B", "I have to find something fast or it gets bad")] },
  { num: 47, answerType: "T1", text: "You hurt your closest person and you're the one who has to start the repair. You're walking up to them.", tap1: [o("A", "my body is heavy"), o("B", "I feel clear and ready"), o("C", "I'm rehearsing it one more time"), o("D", "I want to turn around")], tap2: [o("A", "I lead with what I did wrong"), o("B", "I lead with explaining why"), o("C", "I lead with how I feel"), o("D", "I lead with a question about how they are")] },
  { num: 48, answerType: "T2", text: "Something private about you almost got said out loud in front of people who don't know that thing. The moment passed.", options: [o("A", "I'm shaky for an hour after"), o("B", "I'm furious at the person who almost said it"), o("C", "I feel relief and then a delayed dread"), o("D", "I act fine and lock it down")] },
  { num: 49, answerType: "T3", text: "When you're really stretched thin:", options: [o("A", "I get sharper and more efficient and a little mean"), o("B", "I get foggy and slow and disappear inside")] },
  { num: 50, answerType: "T1", text: "There's something you actually want — a person, a job, a move — and it's close enough to be possible.", tap1: [o("A", "I feel a lift and then a brace"), o("B", "I feel a fear I recognize"), o("C", "I'm already listing reasons it won't work"), o("D", "I feel almost nothing and that's the tell")], tap2: [o("A", "I'm taking the next step this week"), o("B", "I'm waiting for a sign"), o("C", "I'm asking someone whether I should"), o("D", "I'm letting the window close")] },
  { num: 51, answerType: "T2", text: "You're with the one person whose presence actually settles you. You haven't said anything yet.", options: [o("A", "my breathing has already changed"), o("B", "I feel safe enough to feel how tired I am"), o("C", "I'm holding it together so I don't fall apart on them"), o("D", "I can't quite let them in even now")] },
  { num: 52, answerType: "T3", text: "With your closest person, on a normal day:", options: [o("A", "I'm more myself than I am anywhere else"), o("B", "I'm a softer, smaller version of myself I'm not sure is fully me")] },
  { num: 53, answerType: "T2", text: "It's the end of a hard week. You're alone Sunday morning with coffee.", options: [o("A", "I feel quiet and back"), o("B", "I feel hollow and pretending to be back"), o("C", "I'm already gearing up for Monday"), o("D", "I don't know what I feel and I'm not looking")] },
  { num: 54, answerType: "T1", text: "You just realized you haven't felt the low background dread for a couple of days.", tap1: [o("A", "I notice and feel grateful"), o("B", "I notice and immediately wonder when it'll come back"), o("C", "I notice and feel suspicious"), o("D", "I notice and feel a small grief for how long it was there")], tap2: [o("A", "I tell someone"), o("B", "I keep it to myself like a small secret"), o("C", "I try to figure out what I did right so I can repeat it"), o("D", "I let it be without analyzing")] },
  { num: 55, answerType: "T2", text: "Picture the part of you that's been working hardest in your life lately — the one doing the most carrying. If you could turn toward it right now:", options: [o("A", "I feel warmth toward it and want to thank it"), o("B", "I feel impatient with it and want it to rest"), o("C", "I can't quite locate it"), o("D", "I feel a tenderness I wasn't expecting")] },
];
